#!/usr/bin/env ruby -rubygems

require_relative 'modules/f'
require_relative 'modules/utilities'
require_relative 'lib/bca_tree'


def bca_tree
  puts "Enter the tournament URL"
  BcaTree.new(gets.chomp).parse_and_write
end

F.file_to_env('config.anysoft')
bca_tree
